const constants = {
  API_URL: 'https://60122a9f5fffd800170894b8.mockapi.io/DangCap1/',
  REGEX_EMAIL: /^([\w.%+-]+)@([\w-]+\.)+([\w]{2,})$/i,
  REGEX_CURRENCY: /(\d)(?=(\d{3})+(?!\d))/g,
  SIZE_PER_PAGE: 10,
  SIZE_PER_PAGE_LIST: [5, 10, 25, 50, 100],

  GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
  GET_ALL_PRODUCT_SUCCESS: 'GET_ALL_PRODUCT_SUCCESS',
  GET_ALL_PRODUCT_FAILED: 'GET_ALL_PRODUCT_FAILED',

  FILTER_PRODUCT: '  FILTER_PRODUCT',
  FILTER_PRODUCT_SUCCESS: '  FILTER_PRODUCT_SUCCESS',

  ADD_PRODUCT: 'ADD_PRODUCT',
  ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_PRODUCT_FAILED: 'ADD_PRODUCT_FAILED',
  SET_EDIT_DATA: 'SET_EDIT_DATA',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  UPDATE_PRODUCT_SUCCESS: 'UPDATE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT_FAILED: 'UPDATE_PRODUCT_FAILED',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
  DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',
  SEARCH: {
    SEARCH_PRODUCT: 'SEARCH_PRODUCT',
    SEARCH_PRODUCT_SUCCESS: 'SEARCH_PRODUCT_SUCCESS',
    SEARCH_PRODUCT_FAILED: 'SEARCH_PRODUCT_FAILED',
  },
  STATUS: {
    SUCCESS: 200,
    CREATED: 201,
    UPDATE: 202,
  },
  LOADING: {
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
  },
  MODAL: {
    OPEN_MODAL: 'OPEN_MODAL',
    CLOSE_MODAL: 'CLOSE_MODAL',
    CHANGE_MODAL_TITLE: 'CHANGE_MODAL_TITLE',
    CHANGE_MODAL_CONTENT: 'CHANGE_MODAL_CONTENT',
  },
  REDUX_FORM: {
    FORM_NAME: 'FORM_NAME',
  },
  CATEGORY:{
    GET_ALL_CATEGORY: 'GET_ALL_CATEGORY',
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILED: 'GET_ALL_CATEGORY_FAILED',
  }
};
export default constants;
